### ISSUE TITLE
Parse left/right appendages

### ISSUE THREAD

**Issue by MayaGans** [msdvcii/Human-Body-Rendering-HTML#1]
I LOVE this library thank you so much I think it will be an incredibly useful teaching tool! I was wondering since I'm VERY new to using SVGs how difficult it would be to parse the left and right hands/feet/arms/legs from one another? I tried playing around deleting numbers in the paths but I don't think that the right way to go :) Any tips? Thank you SO much for this tool!

**Comment by volcanioo** [comment]
Yeeey! I am so glad for your comment. Thanks for the inspiration, I have some solutions for this.

1. We should change SVG files for this. We can separate from Illustrator. After that, we can implement better than the older one.
2. We can create some elements and can use `background-clip` to smash the elements.

I have a task now. When I finish my task, I can help you with this issue. If you want to do something about it, I can help you.

**Comment by MayaGans** [comment]
I'm using Inkscape to manually break up the files into left & right hands, legs, feet, arms, and shoulders, then using brute force to figure out where the limbs should go using css margins. I'm not sure this is the most efficient way? I can make a PR for you to review when I finish - thanks again! -- I added this in PR #2, you may want to change the viewboxes and shift the positions a little but I think the main idea comes across? Thanks again!

**Comment by volcanioo** [comment]
I'll fix CSS issues. It looks amazing. When I finish CSS issues I'll finish that issue. We should fix that position problems without margins. I will work. Thanks for your contribution!

**Comment by volcanioo** [comment]
Hey @MayaGans,

Your issue is done. Thanks for your contribution.
